/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory, } from "@stencil/router";
import { FactInterface, QAndAInterface, } from "./global/definitions/definitions";
export namespace Components {
    interface AppAbout {
        "history": RouterHistory;
    }
    interface AppArticle {
        "history": RouterHistory;
        "match": MatchResults;
    }
    interface AppArticles {
        "history": RouterHistory;
    }
    interface AppHome {
        "history": RouterHistory;
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface CompFactCarousel {
        "announceItem": boolean;
        "compTitle": string;
        "facts": FactInterface[];
    }
    interface CompGlobalFooter {
    }
    interface CompGlobalHeader {
    }
    interface CompTiles {
        "qAndAData": QAndAInterface;
    }
    interface CompWelcomeBanner {
    }
}
declare global {
    interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {
    }
    var HTMLAppAboutElement: {
        prototype: HTMLAppAboutElement;
        new (): HTMLAppAboutElement;
    };
    interface HTMLAppArticleElement extends Components.AppArticle, HTMLStencilElement {
    }
    var HTMLAppArticleElement: {
        prototype: HTMLAppArticleElement;
        new (): HTMLAppArticleElement;
    };
    interface HTMLAppArticlesElement extends Components.AppArticles, HTMLStencilElement {
    }
    var HTMLAppArticlesElement: {
        prototype: HTMLAppArticlesElement;
        new (): HTMLAppArticlesElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCompFactCarouselElement extends Components.CompFactCarousel, HTMLStencilElement {
    }
    var HTMLCompFactCarouselElement: {
        prototype: HTMLCompFactCarouselElement;
        new (): HTMLCompFactCarouselElement;
    };
    interface HTMLCompGlobalFooterElement extends Components.CompGlobalFooter, HTMLStencilElement {
    }
    var HTMLCompGlobalFooterElement: {
        prototype: HTMLCompGlobalFooterElement;
        new (): HTMLCompGlobalFooterElement;
    };
    interface HTMLCompGlobalHeaderElement extends Components.CompGlobalHeader, HTMLStencilElement {
    }
    var HTMLCompGlobalHeaderElement: {
        prototype: HTMLCompGlobalHeaderElement;
        new (): HTMLCompGlobalHeaderElement;
    };
    interface HTMLCompTilesElement extends Components.CompTiles, HTMLStencilElement {
    }
    var HTMLCompTilesElement: {
        prototype: HTMLCompTilesElement;
        new (): HTMLCompTilesElement;
    };
    interface HTMLCompWelcomeBannerElement extends Components.CompWelcomeBanner, HTMLStencilElement {
    }
    var HTMLCompWelcomeBannerElement: {
        prototype: HTMLCompWelcomeBannerElement;
        new (): HTMLCompWelcomeBannerElement;
    };
    interface HTMLElementTagNameMap {
        "app-about": HTMLAppAboutElement;
        "app-article": HTMLAppArticleElement;
        "app-articles": HTMLAppArticlesElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "comp-fact-carousel": HTMLCompFactCarouselElement;
        "comp-global-footer": HTMLCompGlobalFooterElement;
        "comp-global-header": HTMLCompGlobalHeaderElement;
        "comp-tiles": HTMLCompTilesElement;
        "comp-welcome-banner": HTMLCompWelcomeBannerElement;
    }
}
declare namespace LocalJSX {
    interface AppAbout {
        "history"?: RouterHistory;
    }
    interface AppArticle {
        "history"?: RouterHistory;
        "match"?: MatchResults;
    }
    interface AppArticles {
        "history"?: RouterHistory;
    }
    interface AppHome {
        "history"?: RouterHistory;
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface CompFactCarousel {
        "announceItem"?: boolean;
        "compTitle"?: string;
        "facts"?: FactInterface[];
    }
    interface CompGlobalFooter {
    }
    interface CompGlobalHeader {
    }
    interface CompTiles {
        "qAndAData": QAndAInterface;
    }
    interface CompWelcomeBanner {
    }
    interface IntrinsicElements {
        "app-about": AppAbout;
        "app-article": AppArticle;
        "app-articles": AppArticles;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "comp-fact-carousel": CompFactCarousel;
        "comp-global-footer": CompGlobalFooter;
        "comp-global-header": CompGlobalHeader;
        "comp-tiles": CompTiles;
        "comp-welcome-banner": CompWelcomeBanner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-about": LocalJSX.AppAbout & JSXBase.HTMLAttributes<HTMLAppAboutElement>;
            "app-article": LocalJSX.AppArticle & JSXBase.HTMLAttributes<HTMLAppArticleElement>;
            "app-articles": LocalJSX.AppArticles & JSXBase.HTMLAttributes<HTMLAppArticlesElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "comp-fact-carousel": LocalJSX.CompFactCarousel & JSXBase.HTMLAttributes<HTMLCompFactCarouselElement>;
            "comp-global-footer": LocalJSX.CompGlobalFooter & JSXBase.HTMLAttributes<HTMLCompGlobalFooterElement>;
            "comp-global-header": LocalJSX.CompGlobalHeader & JSXBase.HTMLAttributes<HTMLCompGlobalHeaderElement>;
            "comp-tiles": LocalJSX.CompTiles & JSXBase.HTMLAttributes<HTMLCompTilesElement>;
            "comp-welcome-banner": LocalJSX.CompWelcomeBanner & JSXBase.HTMLAttributes<HTMLCompWelcomeBannerElement>;
        }
    }
}
